const page = require('page')
const autorizacion = require('../utils/autorizacion')
const loader = require('../loader')
const {menu, navbar} = require('../navbar')
const template = require('./template')
const empty = require('empty-element')
const {tipoUsuario} = require('./utils')
page('/usuario/crear', autorizacion(4), loader, menu, navbar, tipoUsuario, (ctx, next) => {
  let container = document.getElementById('main-container')
  empty(container).appendChild(template(ctx.params.tipoUsuario))
})
