const page = require('page')
const autorizacion = require('../utils/autorizacion')
const loader = require('../loader')
const {menu, navbar} = require('../navbar')
const {buscarUsuarios} = require('./utils')
const template = require('./template')
const empty = require('empty-element')
page('/usuario/ver', autorizacion(4), loader, menu, navbar, buscarUsuarios, (ctx, next) => {
  let container = document.getElementById('main-container')
  empty(container).appendChild(template(ctx.params.usuarios))
})
